apiVersion: v1
kind: Service
metadata:
  name: cloud-service-provider
  labels:
    app: cloud-service-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cloud-service-provider