apiVersion: v1
kind: Service
metadata:
  name: ai-technology-provider
  labels:
    app: ai-technology-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai-technology-provider